### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by DongyangHuLi** [youmi-zym/CompletionFormer#1]
Hi, thank you for your open source code.

I have noticed that the epoch of training is 250! I would like to ask how long does it take in total, and why does it need to train so many epochs? BTW, The training sample appears to use only part of the data(76842/85896). Could you tell me why and how you did it?
Thank you so much.

Best,
Hu Li

**Comment by youmi-zym** [comment]
Hi Hu,

Thanks for your interest in our work. The mentioned training is only for KITTI submission, it takes nearly 2-3 weeks with 8 GPUs. It's quite common for most depth completion methods due to the large image resolution of the KITTI dataset. Actually, you will get a better result than NLSPN with just several days of training. For experiments not targeted for benchmark, usually, 100 epochs are appreciated. 

We generate training samples following NLSPN. If I remember right, the number of training samples is 85896. Maybe both of us can check again.

Bests,
Youmin

**Comment by DongyangHuLi** [comment]
> Hi Hu,
> 
> Thanks for your interest in our work. The mentioned training is only for KITTI submission, it takes nearly 2-3 weeks with 8 GPUs. It's quite common for most depth completion methods due to the large image resolution of the KITTI dataset. Actually, you will get a better result than NLSPN with just several days of training. For experiments not targeted for benchmark, usually, 100 epochs are appreciated.
> 
> We generate training samples following NLSPN. If I remember right, the number of training samples is 85896. Maybe both of us can check again.
> 
> Bests, Youmin

Thank you for your prompt reply!

According to your statement, does your model converge until the 250th epoch in KITTI online evaluation dataset?
Can you provide training log and the paper of CVPR2023? Only a different version of the paper is available, but the results in it do not seem to be the best result in KITTI submission. About the training samples, I will check again.

Thank you again.

**Comment by DongyangHuLi** [comment]
> 
Well, thank you for your nice work！
I will close this issue.
